defaults: &defaults
  app_name: "我爱看美剧"
  weibo_key: "146154564"
  weibo_secret: "6bb9ba83bdbb38ecff074d155a27d6c0"
  renren_key: "4742ff74dd124b77a8862b821b72264a"
  renren_secret: "bb3e012024104a8d9d36753193b463ae"
  tqq_key: "801308904"
  tqq_secret: "5288bf6b501c15c5a43cc9ad5c43a611"
  tqq_clientip: "106.187.101.105"
  admin_user_emails: 
    - "bzu_2007@126.com"
    - "wahaha@sina.com.cn"
  xunlei_url: "http://lixian.vip.xunlei.com/lixian_login.html?referfrom=union&ucid=849449175&furl="


development:
  <<: *defaults
  site_url: "http://127.0.0.1:3000/"
  weibo_callback_url: "http://www.wakmj.com:3000/auth/weibo/callback"
  renren_callback_url: "http://www.wakmj.com:3000/auth/renren/callback"
  tqq_callback_url: "http://www.wakmj.com:3000/auth/tqq/callback"
  qq_exmail_user_name: "webmaster@wakmj.com"
  qq_exmail_password: "huangjin0819"
  pic_loc: "/Users/huangjin/Workspace/wakmj.com/public"

test:
  <<: *defaults

  weibo_callback_url: "http://www.wakmj.com:3000/auth/weibo/callback"
  renren_callback_url: "http://www.wakmj.com:3000/auth/renren/callback"
  qq_exmail_user_name: "webmaster@wakmj.com"
  qq_exmail_password: "huangjin0819"

production:
  <<: *defaults
  site_url: "http://www.wakmj.com/"
  weibo_callback_url: "http://www.wakmj.com/auth/weibo/callback"
  renren_callback_url: "http://www.wakmj.com/auth/renren/callback"
  tqq_callback_url: "http://www.wakmj.com/auth/tqq/callback"
  qq_exmail_user_name: "webmaster@wakmj.com"
  qq_exmail_password: "huangjin0819"
  pic_loc: "/home/deploy/www/wakmj/current/public"