defaults: &defaults
  app_name: "我爱看美剧"
  weibo_key: "146154564"
  weibo_secret: "6bb9ba83bdbb38ecff074d155a27d6c0"
  admin_user_emails: 
    - "bzu_2007@126.com"
  xunlei_vod_url: "http://lixian.vip.xunlei.com/lixian_login.html?referfrom=union&ucid=987212&furl="


development:
  <<: *defaults
  site_url: "http://127.0.0.1:3000/"
  weibo_callback_url: "http://www.wakmj.com:3000/auth/weibo/callback"
  qq_exmail_user_name: "webmaster@wakmj.com"
  qq_exmail_password: "huangjin0819"
  pic_loc: "/Users/huangjin/wakmj/public"

test:
  <<: *defaults

  weibo_callback_url: "http://www.wakmj.com:3000/auth/weibo/callback"
  qq_exmail_user_name: "webmaster@wakmj.com"
  qq_exmail_password: "huangjin0819"

production:
  <<: *defaults
  site_url: "http://www.wakmj.com/"
  weibo_callback_url: "http://www.wakmj.com/auth/weibo/callback"
  qq_exmail_user_name: "webmaster@wakmj.com"
  qq_exmail_password: "huangjin0819"
  pic_loc: "/home/deploy/www/wakmj/current/public"